services:
  db:
    container_name: food_sharing
    image: postgres:14.6
    ports:
      - "5432:5432"
    expose:
      - 5432
    env_file:
      - .env
    environment:
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - .:/docker-entrypoint-initdb.d
