"""Added user_id for Profile

Revision ID: 96cd3cbf839a
Revises: 59557547e466
Create Date: 2025-08-16 20:11:44.089385

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96cd3cbf839a"
down_revision: Union[str, None] = "59557547e466"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profile", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "profile", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profile", type_="foreignkey")
    op.drop_column("profile", "user_id")
    # ### end Alembic commands ###
